routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', ['as' => 'LoginAdmin', 'uses' => 'Admin\UserController@getLogin']);
Route::post('admin/login', ['as' => 'PostLoginAdmin', 'uses' => 'Admin\UserController@postLogin']);
Route::get('admin', 'Controller@indexDasboard')->middleware('admin');
/* /========================ROUTE FOR ADMIN========================/ */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['admin']], function () {
	// User
    Route::resource('users', 'UserController')->except(['destroy'
    ]);
    Route::get('users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    // Category
    Route::resource('categories', 'CategoryController')->except(['destroy'
    ]);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'CategoryController@destroy']);
    // Product
    Route::resource('products', 'ProductController')->except(['destroy'
    ]);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductController@destroy']);
    // New
    Route::resource('news', 'NewsController')->except(['destroy'
    ]);
    Route::get('news/destroy/{id}', ['as' => 'news.destroy', 'uses' => 'NewsController@destroy']);
    // Order
    Route::resource('orders', 'OrderController')->except(['destroy','create','store']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'OrderController@destroy']);

    // Contact
    Route::resource('contacts', 'ContactController')->except(['destroy','edit','update', 'create', 'store']);
    Route::get('contacts/destroy/{id}', ['as' => 'contacts.destroy', 'uses' => 'ContactController@destroy']);

    // Slide
    Route::resource('slides', 'SlideController')->except(['destroy','show']);
    Route::get('slides/destroy/{id}', ['as' => 'slides.destroy', 'uses' => 'SlideController@destroy']);


});


Route::get('/', ['as' => 'trangChu','uses'=>'HomepageController@index']);
Route::get('mua-hang',['as' => 'muaHang', 'uses' => 'ShoppingController@index']);
Route::get('them-san-pham/{id}',['as'=>'addSP', 'uses'=>'ShoppingController@add']);
Route::get('xoa-san-pham/{id}',['as'=>'xoaSP', 'uses'=>'ShoppingController@delete']);
Route::put('update-san-pham/{id}',['as'=>'updateSP', 'uses'=>'ShoppingController@update']);
Route::get('thanh-toan', ['as' => 'checkout', 'uses'=>'ShoppingController@checkout']);
Route::post('thanh-toan', ['as'=>'doCheckout', 'uses' => 'ShoppingController@doCheckout']);

Route::get('danh-muc/{slug}', ['as' => 'danh-muc', 'uses'=>'CategoryController@getCategory']);
Route::get('san-pham/{slug}',['as'=>'san-pham','uses'=>'CategoryController@getSP']);

Route::get('tin-tuc/{id}', ['as' => 'tin-tuc', 'uses'=>'CategoryController@getTinTuc']);
Route::get('chi-tiet/{id}', ['as' => 'chi-tiet', 'uses'=>'CategoryController@getChiTiet']);

Route::get('lien-he', ['as' => 'lien-he', 'uses'=>'HomepageController@getContact']);
Route::post('lien-he', ['as' => 'post-lien-he', 'uses'=>'HomepageController@postContact']);

Route::post('search', ['as' => 'search', 'uses'=> 'SearchController@search']);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    protected $fillable = ['name','description','status', 'parent_id','type', 'order','isIndex'];

    public function Product(){
    	return $this->hasMany('App\Product');
    }

    public function New(){
    	return $this->hasMany('App\New');
    }

    public function Childs(){
    	return $this->hasMany('App\Category', 'parent_id');
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = Category::create($request->all());

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findorFail($id);

        return view('admin.category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $category = Category::findorFail($id);

        return view('admin.category.edit', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findorFail($id);

        $category->update($request->all());

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findorFail($id);
        $category->delete();
        return redirect()->route('categories.index');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\News;

class CategoryController extends Controller
{
    public function getCategory($slug){
    	$category = Category::where('slug', $slug)->first();
    	$products = Product::where('category_id', $category->id)->paginate(2);
    	$sidebar = Product::where('category_id', $category->id)->orderBy('created_at', 'ASC')->get()->take(10);
    	return view('client.danhmuc', compact('products','category','sidebar'));
    }

    public function getSP($slug){
    	$product = Product::where('slug', $slug)->first();
    	$sidebar = Product::where('category_id', $product->category_id)->orderBy('created_at', 'ASC')->get()->take(10);
    	$productRelevant = Product::where('category_id', $product->category_id)->orderBy('created_at', 'DESC')->get()->take(10);
    	return view('client.sanpham', compact('product','sidebar','productRelevant'));    
    }

    public function getTinTuc($id){
        $category = Category::findorfail($id);
        $tintucs = News::where('category_id', $id)->paginate(10);
        $sidebar = Category::where('type', 2)->orderBy('created_at', 'ASC')->get()->take(10);
        return view('client.tintuc', compact('category', 'tintucs','sidebar'));
    }

    public function getChiTiet($id){
        $new = News::findorFail($id);
        $sidebar = Category::where('type', 2)->orderBy('created_at', 'ASC')->get()->take(10);

        return view('client.chitiet', compact('new', 'sidebar'));
    }
}

resources/views/admin/category/create.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Danh muc</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ Form::open(['route' => 'categories.store','method' => 'POST']) }}
                                <div class="form-group">
                                    <label>Tên</label>
                                    <input type="text" name="name" required="" class="form-control" placeholder="Nhập tên">
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea class="form-control" name="description" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Status</label>
                                    <select class="form-control" name="status">
                                        <option value="1">Hien Thi</option>
                                        <option value="0">An</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Loai</label>
                                    <select class="form-control" name="type">
                                        <option value="1">San pham</option>
                                        <option value="2">Tin Tuc</option>
                                        <option value="3">Page</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Hien thi trang chu</label>
                                    <select class="form-control" name="isIndex">
                                        <option value="0">Khong</option>
                                        <option value="1">Co</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Danh Muc</label>
                                    <select class="form-control" name="parent_id">
                                        <option value="0">Cha</option>
                                        @if(isset($categories))
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                        @endif
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-default">Gởi</button>
                                <button type="reset" class="btn btn-default">Làm mới</button>
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()

resources/views/admin/category/edit.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Sua Danh muc</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ Form::open(['route' => ['categories.update', $category->id],'method' => 'PUT']) }}
                                <div class="form-group">
                                    <label>Tên</label>
                                    <input type="text" name="name" class="form-control" placeholder="Nhập tên" value="{{$category->name}}">
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea class="form-control" name="description" rows="3">{{$category->description}}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Status</label>
                                    <select class="form-control" name="status">
                                        @if($category->status == "1")
                                        <option value="1" selected="">Hien Thi</option>
                                        <option value="0">An</option>
                                        @else
                                        <option value="1">Hien Thi</option>
                                        <option value="0" selected="">An</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Loai</label>
                                    <select class="form-control" name="type">
                                        @if($category->type == 1)
                                        <option value="1" selected="">San pham</option>
                                        <option value="2">Tin Tuc</option>
                                        <option value="3">Page</option>
                                        @elseif($category->type == 2)
                                        <option value="1">San pham</option>
                                        <option value="2" selected="">Tin Tuc</option>
                                        <option value="3">Page</option>
                                        @else
                                        <option value="1">San pham</option>
                                        <option value="2">Tin Tuc</option>
                                        <option value="3" selected="">Page</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Hien thi trang chu</label>
                                    <select class="form-control" name="isIndex">
                                        @if($category->isIndex == 0)
                                        <option selected="" value="0">Khong</option>
                                        <option value="1">Co</option>
                                        @else
                                        <option value="0">Khong</option>
                                        <option selected="" value="1">Co</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Danh Muc</label>
                                    <select class="form-control" name="parent_id">
                                        <option value="0">Cha</option>
                                        @if(isset($categories))
                                        @foreach($categories as $cate)
                                            <option value="{{$cate->id}}" 
                                                @if($category->parent_id == $cate->id) selected="" @endif
                                            >{{$cate->name}}</option>
                                        @endforeach
                                        @endif
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-default">Gởi</button>
                                <button type="reset" class="btn btn-default">Làm mới</button>
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()

resources/views/admin/category/index.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Categories</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href ="{{route('categories.create')}}" class="btn btn-primary">Thêm mới</a>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Tên</th>
                                <th>Status</th>
                                <th>Thuoc danh muc</th>
                                <th>Loai danh muc</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                                <tr class="odd gradeX">
                                    <td>{{$category->name}}</td>
                                    <td>
                                        @if($category->status == 1)
                                            Hien    
                                        @else
                                            An
                                        @endif
                                    </td>
                                    <td>
                                        <?php
                                        $cate = \App\Category::find($category->parent_id);
                                        if ($cate == null) {
                                            echo "Day la danh muc cha";
                                        } else {
                                            echo $cate->name;
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        @if($category->type == 1)
                                            San pham
                                        @elseif($category->type == 2)
                                            Tin tuc
                                        @else
                                            Static
                                        @endif
                                    </td>
                                    <td>
                                        <a href ="{{route('categories.edit', $category->id)}}" class="btn btn-info">Sửa</a>
                                        <a href ="{{route('categories.show', $category->id)}}" class="btn btn-primary">Hien Thi</a>
                                        <a href ="{{route('categories.destroy', $category->id)}}" class="btn btn-danger" onclick="return confirm('Xóa danh muc {{$category->name}}')">Xóa</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->

@endsection

@section('css')
<!-- DataTables CSS -->
<link href="{{asset('assets/admin/vendor/datatables-plugins/dataTables.bootstrap.css')}}" rel="stylesheet">

<!-- DataTables Responsive CSS -->
<link href="{{asset('assets/admin/vendor/datatables-responsive/dataTables.responsive.css')}}" rel="stylesheet">
@endsection

resources/views/admin/category/show.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Hien thi Danh muc</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Tên</label>
                                    <p class="form-control-static">{{$category->name}}</p>
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <p class="form-control-static">{{$category->description}}</p>
                                </div>
                                <div class="form-group">
                                    <label>Status</label>
                                    <p class="form-control-static">
                                        @if($category->status == "1")
                                            Hien thi
                                        @else
                                            An
                                        @endif
                                    </p>
                                </div>
                                <div class="form-group">
                                    <label>Loai</label>
                                    <p class="form-control-static">
                                        @if($category->type == 1)
                                        San Pham
                                        @elseif($category->type == 2)
                                        Tic tuc
                                        @else
                                        Static
                                        @endif
                                    </p>
                                </div>
                                <div class="form-group">
                                    <label>Danh Muc</label>
                                    <p class="form-control-static">
                                        <?php
                                        $cate = \App\Category::find($category->parent_id);
                                        if ($cate == null) {
                                            echo "Day la danh muc cha";
                                        } else {
                                            echo $cate->name;
                                        }
                                        ?>
                                    </p>
                                </div>
                                <a href="{{route('categories.edit', $category->id)}}" class="btn btn-default">Edit</a>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()