routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', ['as' => 'LoginAdmin', 'uses' => 'Admin\UserController@getLogin']);
Route::post('admin/login', ['as' => 'PostLoginAdmin', 'uses' => 'Admin\UserController@postLogin']);
Route::get('admin', 'Controller@indexDasboard')->middleware('admin');
/* /========================ROUTE FOR ADMIN========================/ */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['admin']], function () {
	// User
    Route::resource('users', 'UserController')->except(['destroy'
    ]);
    Route::get('users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    // Category
    Route::resource('categories', 'CategoryController')->except(['destroy'
    ]);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'CategoryController@destroy']);
    // Product
    Route::resource('products', 'ProductController')->except(['destroy'
    ]);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductController@destroy']);
    // New
    Route::resource('news', 'NewsController')->except(['destroy'
    ]);
    Route::get('news/destroy/{id}', ['as' => 'news.destroy', 'uses' => 'NewsController@destroy']);
    // Order
    Route::resource('orders', 'OrderController')->except(['destroy','create','store']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'OrderController@destroy']);

    // Contact
    Route::resource('contacts', 'ContactController')->except(['destroy','edit','update', 'create', 'store']);
    Route::get('contacts/destroy/{id}', ['as' => 'contacts.destroy', 'uses' => 'ContactController@destroy']);

    // Slide
    Route::resource('slides', 'SlideController')->except(['destroy','show']);
    Route::get('slides/destroy/{id}', ['as' => 'slides.destroy', 'uses' => 'SlideController@destroy']);


});


Route::get('/', ['as' => 'trangChu','uses'=>'HomepageController@index']);
Route::get('mua-hang',['as' => 'muaHang', 'uses' => 'ShoppingController@index']);
Route::get('them-san-pham/{id}',['as'=>'addSP', 'uses'=>'ShoppingController@add']);
Route::get('xoa-san-pham/{id}',['as'=>'xoaSP', 'uses'=>'ShoppingController@delete']);
Route::put('update-san-pham/{id}',['as'=>'updateSP', 'uses'=>'ShoppingController@update']);
Route::get('thanh-toan', ['as' => 'checkout', 'uses'=>'ShoppingController@checkout']);
Route::post('thanh-toan', ['as'=>'doCheckout', 'uses' => 'ShoppingController@doCheckout']);

Route::get('danh-muc/{slug}', ['as' => 'danh-muc', 'uses'=>'CategoryController@getCategory']);
Route::get('san-pham/{slug}',['as'=>'san-pham','uses'=>'CategoryController@getSP']);

Route::get('tin-tuc/{id}', ['as' => 'tin-tuc', 'uses'=>'CategoryController@getTinTuc']);
Route::get('chi-tiet/{id}', ['as' => 'chi-tiet', 'uses'=>'CategoryController@getChiTiet']);

Route::get('lien-he', ['as' => 'lien-he', 'uses'=>'HomepageController@getContact']);
Route::post('lien-he', ['as' => 'post-lien-he', 'uses'=>'HomepageController@postContact']);

Route::post('search', ['as' => 'search', 'uses'=> 'SearchController@search']);

resources/views/layout/admin/sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-users"></i> Users<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('users.index')}}">List</a>
                    </li>
                    <li>
                        <a href="{{route('users.create')}}">Add New</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-list"></i> Categories<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('categories.index')}}">List</a>
                    </li>
                    <li>
                        <a href="{{route('categories.create')}}">Add New</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-cube"></i> Products<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('products.index')}}">List</a>
                    </li>
                    <li>
                        <a href="{{route('products.create')}}">Add New</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-newspaper-o"></i> News<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('news.index')}}">List</a>
                    </li>
                    <li>
                        <a href="{{route('news.create')}}">Add New</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="{{route('orders.index')}}"><i class="fa fa-shopping-cart fa-fw"></i> Hóa Đơn</a>
            </li>
            <li>
                <a href="{{route('contacts.index')}}"><i class="fa fa-phone"></i> Contact</a>
            </li>
            <li>
                <a href="#"><i class="fa-file-image-o"></i> Slides<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('slides.index')}}">List</a>
                    </li>
                    <li>
                        <a href="{{route('slides.create')}}">Add New</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>