routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', ['as' => 'LoginAdmin', 'uses' => 'Admin\UserController@getLogin']);
Route::post('admin/login', ['as' => 'PostLoginAdmin', 'uses' => 'Admin\UserController@postLogin']);
Route::get('admin', 'Controller@indexDasboard')->middleware('admin');
/* /========================ROUTE FOR ADMIN========================/ */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['admin']], function () {
	// User
    Route::resource('users', 'UserController')->except(['destroy'
    ]);
    Route::get('users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    // Category
    Route::resource('categories', 'CategoryController')->except(['destroy'
    ]);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'CategoryController@destroy']);
    // Product
    Route::resource('products', 'ProductController')->except(['destroy'
    ]);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductController@destroy']);
    // New
    Route::resource('news', 'NewsController')->except(['destroy'
    ]);
    Route::get('news/destroy/{id}', ['as' => 'news.destroy', 'uses' => 'NewsController@destroy']);
    // Order
    Route::resource('orders', 'OrderController')->except(['destroy','create','store']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'OrderController@destroy']);

    // Contact
    Route::resource('contacts', 'ContactController')->except(['destroy','edit','update', 'create', 'store']);
    Route::get('contacts/destroy/{id}', ['as' => 'contacts.destroy', 'uses' => 'ContactController@destroy']);

    // Slide
    Route::resource('slides', 'SlideController')->except(['destroy','show']);
    Route::get('slides/destroy/{id}', ['as' => 'slides.destroy', 'uses' => 'SlideController@destroy']);


});


Route::get('/', ['as' => 'trangChu','uses'=>'HomepageController@index']);
Route::get('mua-hang',['as' => 'muaHang', 'uses' => 'ShoppingController@index']);
Route::get('them-san-pham/{id}',['as'=>'addSP', 'uses'=>'ShoppingController@add']);
Route::get('xoa-san-pham/{id}',['as'=>'xoaSP', 'uses'=>'ShoppingController@delete']);
Route::put('update-san-pham/{id}',['as'=>'updateSP', 'uses'=>'ShoppingController@update']);
Route::get('thanh-toan', ['as' => 'checkout', 'uses'=>'ShoppingController@checkout']);
Route::post('thanh-toan', ['as'=>'doCheckout', 'uses' => 'ShoppingController@doCheckout']);

Route::get('danh-muc/{slug}', ['as' => 'danh-muc', 'uses'=>'CategoryController@getCategory']);
Route::get('san-pham/{slug}',['as'=>'san-pham','uses'=>'CategoryController@getSP']);

Route::get('tin-tuc/{id}', ['as' => 'tin-tuc', 'uses'=>'CategoryController@getTinTuc']);
Route::get('chi-tiet/{id}', ['as' => 'chi-tiet', 'uses'=>'CategoryController@getChiTiet']);

Route::get('lien-he', ['as' => 'lien-he', 'uses'=>'HomepageController@getContact']);
Route::post('lien-he', ['as' => 'post-lien-he', 'uses'=>'HomepageController@postContact']);

Route::post('search', ['as' => 'search', 'uses'=> 'SearchController@search']);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Product extends Model
{
	use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    protected $fillable = ['name','price','short_description', 'long_description','image','unit','category_id'];

    public function Category(){
    	return $this->belongsTo('App\Category', 'category_id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use Image;
use App\Category;
use File;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.product.index', compact('products'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('type',1)->get();
        return view('admin.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->image;

        $filename  = time() . '.' . $image->getClientOriginalExtension();

        $path = public_path('uploads/' . $filename);

        Image::make($image->getRealPath())->resize(200, 200)->save($path);

        $product = new Product;

        $data = $request->all();

        $data['image'] = $filename;
        
        $product = Product::create($data);

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findorFail($id);

        return view('admin.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::where('type',1)->get();
        $product = Product::findorFail($id);
        return view('admin.product.edit', compact('categories','product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findorFail($id);

        if(isset($request->image)) {
            $image_path = public_path()."/uploads/".$product->image;
            if(File::exists($image_path)) {
                File::delete($image_path);
            }
            $image = $request->image;

            $filename  = time() . '.' . $image->getClientOriginalExtension();

            $path = public_path('uploads/' . $filename);

            Image::make($image->getRealPath())->resize(200, 200)->save($path);

            $data = $request->all();

            $data['image'] = $filename;
            
            $product->update($data);
            return redirect()->route('products.index');
        }

        $product->update($request->all());

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findorFail($id);

        if ($product->image) {
            $image_path = public_path()."/uploads/".$product->image;
            if(File::exists($image_path)) {
                File::delete($image_path);
            }
        }

        $product->delete();

        return redirect()->route('products.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('layout.admin.masterLayout')
@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Product</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ Form::open(['route' => 'products.store','method' => 'POST','files' => true]) }}
                                <div class="form-group">
                                    <label>Tên</label>
                                    <input type="text" name="name" class="form-control" placeholder="Nhập tên">
                                </div>
                                <div class="form-group">
                                    <label>Price</label>
                                    <input tpye="text" name="price" class="form-control" placeholder="Nhập Gia">
                                </div>
                                <div class="form-group">
                                    <label>Don vi (Unit)</label>
                                    <input tpye="text" name="unit" class="form-control" placeholder="Nhập Don Vi">
                                </div>
                                <div class="form-group">
                                    <label>Anh</label>
                                    <input type="file" name="image">
                                </div>
                                <div class="form-group">
                                    <label>Mo ta ngan</label>
                                    <textarea class="form-control" name="short_description" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Mo ta</label>
                                    <textarea class="form-control" id="product_long_description" name="long_description" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Danh Muc</label>
                                        <select class="form-control" name="category_id">
                                            @foreach($categories as $category)
                                                <option value="{{$category->id}}">{{$category->name}}</option>
                                            @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-default">Gởi</button>
                                <button type="reset" class="btn btn-default">Làm mới</button>
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()

resources/views/admin/product/edit.blade.php
@extends('layout.admin.masterLayout')
@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Product</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ Form::open(['route' => ['products.update', $product->id],'method' => 'PUT', 'files' => true]) }}
                                <div class="form-group">
                                    <label>Tên</label>
                                    <input type="text" name="name" class="form-control" placeholder="Nhập tên" value="{{$product->name}}">
                                </div>
                                <div class="form-group">
                                    <label>Price</label>
                                    <input tpye="text" name="price" class="form-control" placeholder="Nhập Gia" value="{{$product->price}}">
                                </div>
                                <div class="form-group">
                                    <label>Don vi (Unit)</label>
                                    <input tpye="text" name="unit" class="form-control" placeholder="Nhập Don Vi" value="{{$product->unit}}">
                                </div>
                                <div class="form-group">
                                    <label>Anh</label>
                                    <img src="{{asset('uploads/'.$product->image)}}" width="300", height="300"/>
                                    <input type="file" name="image" style="padding-top: 10px;">
                                </div>
                                <div class="form-group">
                                    <label>Mo ta ngan</label>
                                    <textarea class="form-control" name="short_description" rows="3">{{$product->short_description}}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Mo ta</label>
                                    <textarea class="form-control" id="product_long_description" name="long_description" rows="3">{!!$product->long_description!!}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Danh Muc</label>
                                        <select class="form-control" name="category_id">
                                            @foreach($categories as $cate)
                                                <option value="{{$cate->id}}"
                                                    @if($cate->id == $product->category_id) selected="" @endif
                                                    >{{$cate->name}}</option>
                                            @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-default">Gởi</button>
                                <button type="reset" class="btn btn-default">Làm mới</button>
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()

resources/views/admin/product/index.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Product</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href ="{{route('products.create')}}" class="btn btn-primary">Thêm mới</a>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Tên</th>
                                <th>Price</th>
                                <th>Danh Muc</th>
                                <th>Hinh Anh</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products as $product)
                                <tr class="odd gradeX">
                                    <td>{{$product->name}}</td>
                                    <td>{{number_format($product->price), 2}}</td>
                                    <td>{{$product->Category->name}}</td>
                                    <td><img src="{{asset('uploads/'.$product->image)}}" width="50px", height="50px" /></td>
                                        <td><a href ="{{route('products.edit', $product->id)}}" class="btn btn-info">Sửa</a>
                                        <a href ="{{route('products.show', $product->id)}}" class="btn btn-primary">Hien Thi</a>
                                        <a href ="{{route('products.destroy', $product->id)}}" class="btn btn-danger" onclick="return confirm('Xóa hinh anh {{$product->name}}')">Xóa</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->

@endsection

@section('css')
<!-- DataTables CSS -->
<link href="{{asset('assets/admin/vendor/datatables-plugins/dataTables.bootstrap.css')}}" rel="stylesheet">

<!-- DataTables Responsive CSS -->
<link href="{{asset('assets/admin/vendor/datatables-responsive/dataTables.responsive.css')}}" rel="stylesheet">
@endsection

resources/views/admin/product/show.blade.php
@extends('layout.admin.masterLayout')
@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Hien Thi</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Tên</label>
                                    <p class="form-control-static">{{$product->name}}</p>
                                </div>
                                <div class="form-group">
                                    <label>Price</label>
                                    <p class="form-control-static">{{$product->price}}</p>
                                </div>
                                <div class="form-group">
                                    <label>Don vi (Unit)</label>
                                    <p class="form-control-static">{{$product->unit}}</p>
                                </div>
                                <div class="form-group">
                                    <label>Anh</label>
                                    <img src="{{asset('uploads/'.$product->image)}}" width="300", height="300"/>
                                </div>
                                <div class="form-group">
                                    <label>Mo ta ngan</label>
                                    <p class="form-control-static">{{$product->short_description}}</p>
                                </div>
                                <div class="form-group">
                                    <label>Mo ta</label>
                                    <p class="form-control-static">{!!$product->long_description!!}</p>
                                </div>
                                <div class="form-group">
                                    <label>Danh Muc</label>
                                    <p class="form-control-static">{{$product->Category->name}}</p>
                                </div>
                                <a href="{{route('products.edit', $product->id)}}" class="btn btn-default">Edit</a>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()