routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', ['as' => 'LoginAdmin', 'uses' => 'Admin\UserController@getLogin']);
Route::post('admin/login', ['as' => 'PostLoginAdmin', 'uses' => 'Admin\UserController@postLogin']);
Route::get('admin', 'Controller@indexDasboard')->middleware('admin');
/* /========================ROUTE FOR ADMIN========================/ */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['admin']], function () {
	// User
    Route::resource('users', 'UserController')->except(['destroy'
    ]);
    Route::get('users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    // Category
    Route::resource('categories', 'CategoryController')->except(['destroy'
    ]);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'CategoryController@destroy']);
    // Product
    Route::resource('products', 'ProductController')->except(['destroy'
    ]);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductController@destroy']);
    // New
    Route::resource('news', 'NewsController')->except(['destroy'
    ]);
    Route::get('news/destroy/{id}', ['as' => 'news.destroy', 'uses' => 'NewsController@destroy']);
    // Order
    Route::resource('orders', 'OrderController')->except(['destroy','create','store']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'OrderController@destroy']);

    // Contact
    Route::resource('contacts', 'ContactController')->except(['destroy','edit','update', 'create', 'store']);
    Route::get('contacts/destroy/{id}', ['as' => 'contacts.destroy', 'uses' => 'ContactController@destroy']);

    // Slide
    Route::resource('slides', 'SlideController')->except(['destroy','show']);
    Route::get('slides/destroy/{id}', ['as' => 'slides.destroy', 'uses' => 'SlideController@destroy']);


});


Route::get('/', ['as' => 'trangChu','uses'=>'HomepageController@index']);
Route::get('mua-hang',['as' => 'muaHang', 'uses' => 'ShoppingController@index']);
Route::get('them-san-pham/{id}',['as'=>'addSP', 'uses'=>'ShoppingController@add']);
Route::get('xoa-san-pham/{id}',['as'=>'xoaSP', 'uses'=>'ShoppingController@delete']);
Route::put('update-san-pham/{id}',['as'=>'updateSP', 'uses'=>'ShoppingController@update']);
Route::get('thanh-toan', ['as' => 'checkout', 'uses'=>'ShoppingController@checkout']);
Route::post('thanh-toan', ['as'=>'doCheckout', 'uses' => 'ShoppingController@doCheckout']);

Route::get('danh-muc/{slug}', ['as' => 'danh-muc', 'uses'=>'CategoryController@getCategory']);
Route::get('san-pham/{slug}',['as'=>'san-pham','uses'=>'CategoryController@getSP']);

Route::get('tin-tuc/{id}', ['as' => 'tin-tuc', 'uses'=>'CategoryController@getTinTuc']);
Route::get('chi-tiet/{id}', ['as' => 'chi-tiet', 'uses'=>'CategoryController@getChiTiet']);

Route::get('lien-he', ['as' => 'lien-he', 'uses'=>'HomepageController@getContact']);
Route::post('lien-he', ['as' => 'post-lien-he', 'uses'=>'HomepageController@postContact']);

Route::post('search', ['as' => 'search', 'uses'=> 'SearchController@search']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create($request->all());

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findorFail($id);

        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findorFail($id);
        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findorFail($id);

        $user->update($request->all());

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findorFail($id);
        $user->delete();
        return redirect()->route('users.index');
    }

    public function getLogin(){
        return view('admin.login');
    }

    public function postLogin(Request $request){
        $login = [
            'email' => $request->email,
            'password' => $request->password,
        ];

        $checkLogin = Auth::attempt($login);

        if ($checkLogin) {
            return redirect()->route('orders.index');
        }
        return redirect()->route('LoginAdmin');

    }
}

resources/views/admin/user/create.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Người dùng</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ Form::open(['route' => 'users.store','method' => 'POST']) }}
                                <div class="form-group">
                                    <label>Tên</label>
                                    <input type="text" name="name" class="form-control" placeholder="Nhập tên">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input tpye="text" name="email" class="form-control" placeholder="Nhập Email">
                                </div>
                                <div class="form-group">
                                    <label>Mật khẩu</label>
                                    <input type="password" name="password" class="form-control" placeholder="Mật Khẩu">
                                </div>
                                <button type="submit" class="btn btn-default">Gởi</button>
                                <button type="reset" class="btn btn-default">Làm mới</button>
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()

resources/views/admin/user/edit.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Edit Người dùng</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ Form::open(['route' => ['users.update', $user->id],'method' => 'PUT']) }}
                                <div class="form-group">
                                    <label>Tên</label>
                                    <input type="text" name="name" class="form-control" placeholder="Nhập tên" value="{{$user->name}}">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input tpye="text" name="email" class="form-control" placeholder="Nhập Email" value="{{$user->email}}">
                                </div>
                                <div class="form-group">
                                    <label>Mật khẩu</label>
                                    <input type="password" name="password" class="form-control" placeholder="Mật Khẩu" value="{{$user->password}}">
                                </div>
                                <button type="submit" class="btn btn-default">Gởi</button>
                                <button type="reset" class="btn btn-default">Làm mới</button>
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()

resources/views/admin/user/index.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">User</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href ="{{route('users.create')}}" class="btn btn-primary">Thêm mới</a>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Tên</th>
                                <th>Email</th>
                                <th>Ngày tạo</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr class="odd gradeX">
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->created_at}}</td>
                                        <td><a href ="{{route('users.edit', $user->id)}}" class="btn btn-info">Sửa</a>
                                        <a href ="{{route('users.show', $user->id)}}" class="btn btn-primary">Hien Thi</a>
                                        <a href ="{{route('users.destroy', $user->id)}}" class="btn btn-danger" onclick="return confirm('Xóa người dùng {{$user->name}}')">Xóa</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->

@endsection

@section('css')
<!-- DataTables CSS -->
<link href="{{asset('assets/admin/vendor/datatables-plugins/dataTables.bootstrap.css')}}" rel="stylesheet">

<!-- DataTables Responsive CSS -->
<link href="{{asset('assets/admin/vendor/datatables-responsive/dataTables.responsive.css')}}" rel="stylesheet">
@endsection

resources/views/admin/user/show.blade.php
@extends('layout.admin.masterLayout')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Hien Thi Người dùng</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Tên</label>
                                <p class="form-control-static">{{$user->name}}</p>
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <p class="form-control-static">{{$user->email}}</p>
                            </div>
                            <a href="{{route('users.edit', $user->id)}}" class="btn btn-default">Edit</a>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
@endsection()